theme: cupper

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-multiple-languages-plugin

title: Ka-Kyung Blog
description: Personal research and tech blog
author:
  name: Ka-Kyung Kim
  email: kakyung.kim@gmail.com
social:
  github: kakyungkim
  linkedin: kakyungkim
