title: "Ka-Kyung Blog"
description: "Personal research and tech blog"
author:
  name: "Ka-Kyung Kim"
  email: "kakyung.kim@gmail.com"

remote_theme: "mmistakes/minimal-mistakes"
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-coffeescript
  - jekyll-multiple-languages-plugin
  - jekyll-remote-theme

languages: ["en", "kr"]
default_lang: "kr"
use_default_lang_prefix: true
strategy: prefix

lang_switcher:
  en: "English"
  kr: "한국어"

permalink: /:lang/:year/:month/:day/:title/
